### ISSUE TITLE
Criar opção de bet no menu

### ISSUE THREAD

**Issue by rodrigocam** [Paradigmas2018-02/robopok#2]
Criar opção de bet e consequentemente de all in no menu do jogo que permita ao jogador apostar, uma rota na API deve ser criada para responder a esse post enviado pelo prolog.

**Comment by pablodiegoss** [comment]
Rota de bet já criada no haskell, só necessário passar um value no json para a aposta. Vou começar a trabalhar no acesso disso com o Prolog

**Comment by pablodiegoss** [comment]
Já é possivel digitar o valor da aposta e enviar para o haskell via prolog e requests
